# Generated by Django 5.2.4 on 2025-07-25 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('password', models.CharField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('food and dining', 'Food And Dining'), ('entertainment', 'Entertainment'), ('rent', 'Rent'), ('transportation', 'Transportation'), ('education', 'Education'), ('medical', 'Medical'), ('groceries', 'Groceries'), ('maintenance', 'Maintenance'), ('utilities', 'Utilities'), ('travel', 'Travel'), ('loan payment', 'Loan Payment'), ('insurance', 'Insurance'), ('shopping', 'Shopping'), ('gadgets', 'Gadgets'), ('stationary', 'Stationary')], max_length=300, null=True)),
                ('amount', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('food and dining', 'Food And Dining'), ('entertainment', 'Entertainment'), ('rent', 'Rent'), ('transportation', 'Transportation'), ('education', 'Education'), ('medical', 'Medical'), ('groceries', 'Groceries'), ('maintenance', 'Maintenance'), ('utilities', 'Utilities'), ('travel', 'Travel'), ('loan payment', 'Loan Payment'), ('insurance', 'Insurance'), ('shopping', 'Shopping'), ('gadgets', 'Gadgets'), ('stationary', 'Stationary')], max_length=300, null=True)),
                ('amount', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
