# Generated by Django 5.2.4 on 2025-07-27 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='spent_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='income',
            name='spent_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='savings',
            name='spent_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
